apiVersion: v1
kind: PersistentVolume
metadata:
  name: frontend-volume
  labels:
    type: local
spec:
  storageClassName: "standard"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/host/nginx.conf"