apiVersion: apps/v1
kind: Deployment
metadata:
  name: orthanc
  labels:
    app: orthanc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orthanc
  template:
    metadata:
      labels:
        app: orthanc
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
        - name: task-pv-container
          image: jodogne/orthanc-plugins
          imagePullPolicy: "Never"
          ports:
            - containerPort: 8046
              name: "http-server"
            - containerPort: 4242
              name: "dicom-server"
          volumeMounts:
            - mountPath: "/etc/orthanc"
              name: task-pv-storage